### ISSUE TITLE
Warning:(14, 24) Application namespace for attribute bind:visibilityOnIndex will be ignored.

### ISSUE THREAD

**Issue by MuhSalmaNabila** [mutualmobile/Sherlock#4]
After open and import your code app to my project, this warning occured after I rebuild project.
any solution?

**Comment by mustafa01ali** [comment]
I wasn't able to reproduce this issue on my end. Which file are you getting this error in?

**Comment by mgujare** [comment]
is it still an issue ? I think i had a similar issue in my project only when proguard minification enabled.

**Comment by mustafa01ali** [comment]
Proguard is disabled by default in this project, so that shouldn't be a problem. I'm still unable to repro this hence closing this issue.
